quarkus.application.name=user-service
quarkus.http.port=8090

quarkus.smallrye-openapi.info-title=User Service API
quarkus.swagger-ui.always-include=true

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/user_db

quarkus.hibernate-orm.database.generation=none
quarkus.flyway.migrate-at-start=true
quarkus.flyway.validate-on-migrate=false

quarkus.oidc.auth-server-url=http://localhost:8080/realms/ecommerce
quarkus.oidc.client-id=ecommerce-backend
quarkus.oidc.credentials.secret=ecommerce-backend-secret
quarkus.oidc.application-type=service
quarkus.oidc.roles.role-claim-path=groups

quarkus.log.level=INFO
quarkus.log.category."com.ecommerce".level=DEBUG
quarkus.log.console.json=true
quarkus.log.console.json.additional-field."service".value=${quarkus.application.name}
quarkus.http.cors=true
quarkus.http.cors.origins=*


