# Application
quarkus.application.name=inventory-service
quarkus.http.port=8087

# OpenAPI / Swagger
quarkus.smallrye-openapi.info-title=Inventory Service API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.swagger-ui.always-include=true

# DataSource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=admin
quarkus.datasource.password=admin123
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/inventory_db

# Hibernate
quarkus.hibernate-orm.database.generation=none

# Flyway
quarkus.flyway.migrate-at-start=true

# OIDC
quarkus.oidc.auth-server-url=http://localhost:8080/realms/ecommerce
quarkus.oidc.client-id=ecommerce-backend
quarkus.oidc.credentials.secret=ecommerce-backend-secret
quarkus.oidc.application-type=service
quarkus.oidc.roles.role-claim-path=groups

# ─── Kafka ────────────────────────────────────────────────────────────────────
kafka.bootstrap.servers=localhost:29092

# Incoming: order-created
mp.messaging.incoming.order-created-in.connector=smallrye-kafka
mp.messaging.incoming.order-created-in.topic=order-created
mp.messaging.incoming.order-created-in.group.id=inventory-service
mp.messaging.incoming.order-created-in.value.type=com.ecommerce.common.event.OrderCreatedEvent
mp.messaging.incoming.order-created-in.failure-strategy=dead-letter-queue
mp.messaging.incoming.order-created-in.dead-letter-queue.topic=order-created-dlq

# Outgoing: stock-reserved
mp.messaging.outgoing.stock-reserved-out.connector=smallrye-kafka
mp.messaging.outgoing.stock-reserved-out.topic=stock-reserved

# Incoming: order-confirmed (for compensation — release/confirm stock)
mp.messaging.incoming.order-confirmed-in.connector=smallrye-kafka
mp.messaging.incoming.order-confirmed-in.topic=order-confirmed
mp.messaging.incoming.order-confirmed-in.group.id=inventory-service
mp.messaging.incoming.order-confirmed-in.value.type=com.ecommerce.common.event.OrderConfirmedEvent
mp.messaging.incoming.order-confirmed-in.failure-strategy=dead-letter-queue
mp.messaging.incoming.order-confirmed-in.dead-letter-queue.topic=order-confirmed-dlq

# Logging — structured JSON
quarkus.log.level=INFO
quarkus.log.category."com.ecommerce".level=DEBUG
quarkus.log.console.json=true
quarkus.log.console.json.additional-field."service".value=${quarkus.application.name}

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*


